package com.m2i.charron.hibernet;
// Generated 27 mars 2018 11:28:04 by Hibernate Tools 4.3.1



/**
 * Employer generated by hbm2java
 */
public class Employer  implements java.io.Serializable {


     private Integer id;
     private String ename;
     private String enumber;

    public Employer() {
    }

    public Employer(String ename, String enumber) {
       this.ename = ename;
       this.enumber = enumber;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }
    public String getEnumber() {
        return this.enumber;
    }
    
    public void setEnumber(String enumber) {
        this.enumber = enumber;
    }




}


